### ISSUE TITLE
Define Recipe deployment dependencies

### ISSUE THREAD

**Issue by taliaga** [smartsdk/mongo-rs-controller-swarm#10]
We need to define if having docker-compose.yml depend on external files (as it is now with the healthcheck) is something we want or not.

Nowe we already have extra files to simplify some background setup (networks creation, environment variables setup maybe, etc). But, shouldn't the docker-compose.yml already come with defaults that allow users to deploy the basics as it is?

**Comment by chicco785** [comment]
in general it is not possible with current docker features to have all you need in docker-compose. secrets and configs are there because of that. so, except that with the introduction of config, we should use that rather than secrets, I don't see any issue here.
