### ISSUE TITLE
How do I connect to my mongo cluster

### ISSUE THREAD

**Issue by ticruz38** [smartsdk/mongo-rs-controller-swarm#14]
I really want to apologize for that stupid question, but I can't find a way to connect my app to that mongo cluster, although everything is running as expected.
I got my swarm cluster
```
NAME             ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
mongo-master     -        virtualbox   Running   tcp://192.168.99.103:2376           v17.09.1-ce
mongo-worker-1   -        virtualbox   Running   tcp://192.168.99.104:2376           v17.09.1-ce
mongo-worker-2   -        virtualbox   Running   tcp://192.168.99.105:2376           v17.09.1-ce
```
and my services running with the port publish for my mongo
```
ID                  NAME                MODE                REPLICAS            IMAGE                              PORTS
nohna3vux2of        mongo_controller    replicated          1/1                 martel/mongo-replica-ctrl:latest
mvppe3gwyn27        mongo_mongo         global              3/3                 mongo:3.2                          *:27017->27017/tcp
```
However, which url should I use to connect to my mongo? Also since I publish my port, I have to secure my db by hand right?

Thanks for your help

**Comment by chicco785** [comment]
there is no stupid question :)

is your app containerised or not?

If it is containerised and deployed in the same Docker Swarm cluster, you can apply a simple security by connecting the app to the same network of the mongo, not exposing mongo ports (the current configuration in the docker-compose.yml file), and using `mongo_mongo` as endpoint.

If it is not containerised, you should add the ports to the docker-compose.yml file and connect to any of the ip of your cluster to that port. be aware that depending on the driver you use it may work more or less well with replica set (not all drivers are able to negotiate the ip of the master and connect only to that one).

then, if you wanna have security in this case, you will have to configure the mongo properly.

i hope this helps.

**Comment by taliaga** [comment]
Complementing, using `mongo` (i.e, the [name of the service described in the docker-compose](https://github.com/smartsdk/mongo-rs-controller-swarm/blob/886d8670b645e5a21d6b2756e1ec0127179b5da8/docker-compose.yml#L5)) as the url should suffice (when your service is deployed in the same swarm network). To understand more about why using, refer to [docker's VIP docs](https://docs.docker.com/engine/swarm/networking/#configure-service-discovery).

In any case, as said above, remember to tell your driver that it's actually a replicaset because not all requests to `mongo` will end up in the mongo primary node of the rs.

**Comment by ticruz38** [comment]
ok thanks for your answers! 
I actually found out how to connect, I just want to secure it now. And I would like to take advantage of the cluster of course. Connecting to the master ip with the right mongo port isn't enough? My driver would be javascript one.

**Comment by chicco785** [comment]
do you mean nodejs?

as you can see in the [add-ons](https://github.com/smartsdk/mongo-rs-controller-swarm/blob/master/docker-compose-addons.yml) part, it works fine with https://www.nosqlclient.com/ , which is NodeJS, so it should not be a problem.

The mongo uri we pass to nosqlclient in docker-compose is: `mongodb://${STACK_NAME:-mongo}_mongo:27017/?replicaSet=rs`

**Comment by ticruz38** [comment]
I have it running on a swarm in the cloud. I did uncomment the port line to publish on 27017.
Here are my services
```
ID                  NAME                 MODE                REPLICAS            IMAGE                              PORTS
o3kitedsdom4        client_nosqlclient   replicated          1/1                 mongoclient/mongoclient:2.2.0      *:3000->3000/tcp
xzoeyf9yhng3        mongo_controller     replicated          1/1                 martel/mongo-replica-ctrl:latest
cyby2xlhhjkb        mongo_mongo          global              3/3                 mongo:3.2                          *:27017->27017/tcp
```
However my container do not expose any port 
```
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                       PORTS               NAMES
326d241fbf0a        mongoclient/mongoclient:2.2.0      "./entrypoint.sh nod…"   28 minutes ago      Up 28 minutes                3000/tcp            client_nosqlclient.1.531io1np3ukf1v6v4sp7athp4
495c4a529eec        martel/mongo-replica-ctrl:latest   "python /src/replica…"   About an hour ago   Up About an hour                                 mongo_controller.1.hyzz17ya2d5ioevnxllb7kajv
82b710b242bf        mongo:3.2                          "/usr/bin/mongod --r…"   About an hour ago   Up About an hour (healthy)   27017/tcp           mongo_mongo.i9o9k5ghl4teul2ffq8g
```
I tried to connect using mongodb://myServerIP:27017, but seems like there's nothing here.
I guess I need to find a way to expose my port on the container, otherwise I want be able to connect outside my swarm right?

**Comment by chicco785** [comment]
the behaviour exposed is the correct one, since with swarm containers are configured behind a load balancer and containers actually never publish their port.

to which ip are you connecting? i created a test cluster with miniswarm on my mac:

```
NAME            ACTIVE   DRIVER       STATE     URL                          SWARM   DOCKER        ERRORS
ms-manager0     *        virtualbox   Running   tcp://192.168.99.120:2376            v17.09.1-ce   
ms-worker0      -        virtualbox   Running   tcp://192.168.99.121:2376            v17.09.1-ce   
ms-worker1      -        virtualbox   Running   tcp://192.168.99.122:2376            v17.09.1-ce 
```

testing telnet against the manager seems to be working:
```
$ telnet 192.168.99.120 27017
Trying 192.168.99.120...
Connected to 192.168.99.120.
Escape character is '^]'.
```

also testing it with a mongo client:
```
$ docker run --name client -d mongo:3.2 tail -f /dev/null
Unable to find image 'mongo:3.2' locally
3.2: Pulling from library/mongo
Digest: sha256:c7aafb66542e3db5f63468db5d31dd93251a1391746dbefb48d05d792ce86eef
Status: Downloaded newer image for mongo:3.2
59a68ba621dccfb5e76fecf9b32682bc0e748a1b2e90968d90decc3f3a803d55

$ docker exec client mongo --quiet 192.168.99.120/admin --eval "db.runCommand( { replSetGetStatus : 1 } )['ok']"
1
```
this makes me think that the recipe is working correctly (as also anyhow the automated tests confirms).

did you configure correctly the security on your cloud to allow access to 27017 from your client?

**Comment by ticruz38** [comment]
Well, I did 2 exact same swarm cluster with the same configuration, one is remote and hosted on scaleway, the other one is local with the virtual box driver. 
doing `telnet 192.168.99.100 27017` does connect
doing `telnet myserverip 27017` I get a connection refused
I guess this is related to a security setting on my server. 
What is really strange though is that I can connect to a remote container publishing its port BUT not to a service with port published.
If you have any idea or tips to make it work remotely, or what kind of security settings I should able/disable feel free to share with me ))
I will keep exploring and update you as soon as I found my mistake, I will close it for now as it's probably not related to the mongo replica-set
Thanks for your help!

**Comment by chicco785** [comment]
is your remote mongo cluster on 27012?

**Comment by ticruz38** [comment]
No I corrected, it's on 27017.
Scaleway may not allow publishing 27017, so I tried another port, but I get the same result. Connection refused.

**Comment by chicco785** [comment]
i never used scaleway, but can you ssh in the swarm manager server and test locally? `telnet localhost 27017`

**Comment by ticruz38** [comment]
yes I can connect from localhost. Here are my services.
```
ID                  NAME                MODE                REPLICAS            IMAGE                              PORTS
3d0ojs08z7z4        mongo_controller    replicated          1/1                 martel/mongo-replica-ctrl:latest
v1mfly4ik110        mongo_mongo         global              3/3                 mongo:3.2                          *:27012->27017/tcp
```
here are my containers
```
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                PORTS               NAMES
0e932567bbbf        martel/mongo-replica-ctrl:latest   "python /src/replica…"   5 days ago          Up 5 days                                 mongo_controller.1.x29ya85kfv1xfyhew6wki6jl0
4bf479ccc5ad        mongo:3.2                          "/usr/bin/mongod --r…"   5 days ago          Up 5 days (healthy)   27017/tcp           mongo_mongo.i9o9k5ghl4teul2ffq8g1guc4.jbeiidc4whwjw0qckr8czksyk
```
doing telnet on 27012 and 27017 does connect to localhost
```
root@scaleway-master:/# telnet localhost 27017
Trying ::1...
Connected to localhost.
Escape character is '^]'.
```
I guess the problem is how I publish my port to the external IP?

Sorry for the long delay, I was traveling quite a lot lastly, hard to find a proper wifi. Thanks for your help.

**Comment by chicco785** [comment]
so if by logging on scaleway with ssh you can telnet on 27017, it is surely a problem of configuration of scaleway public ports.

**Comment by ticruz38** [comment]
I will investigate
